CBProject/Models/EntityModels/Review.cs
using CBProject.Models.EntityModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CBProject.Models
{
    public class Review
    {
        public int ID { get; set; }
        [ForeignKey("Reviewer")]
        public string ReviewerId { get; set; }
        public ApplicationUser Reviewer { get; set; }
        public string Comment { get; set; }
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }
        public ICollection<ReviewToEbook> ReviewsToEbooks { get; set; }
        public ICollection<ReviewToVideo> ReviewToVideos { get; set; }
    }
}

CBProject/Models/EntityModels/Tag.cs
using System.Collections.Generic;

namespace CBProject.Models.EntityModels
{
    public class Tag
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public ICollection<TagToEbook> TagsToEbooks { get; set; }
        public ICollection<TagToVideo> TagsToVideos { get; set; }
    }
}

CBProject/Models/ViewModels/TagViewModel.cs
namespace CBProject.Models.ViewModels
{
    public class TagViewModel
    {
        public int ID { get; set; }
        public string Title { get; set; }
    }
}

CBProject/Controllers/API/TagController.cs
using CBProject.HelperClasses;
using CBProject.HelperClasses.Interfaces;
using CBProject.Models.EntityModels;
using CBProject.Repositories;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;

namespace CBProject.Controllers.API
{
    public class TagController : ApiController, IDisposable
    {
        private readonly TagsRepository _tagsRepository;

        public TagController(IUnitOfWork unitOfWork)
        {
            this._tagsRepository = unitOfWork.Tags;
        }

        // GET api/Tag
        [HttpGet]
        [Route("api/Tag/all")]
        public async Task<IHttpActionResult> Get()
        {
            var tags = await this._tagsRepository.GetAllAsync();
            return Ok(tags);
        }

        // GET api/Tag/5
        public async Task<IHttpActionResult> Get(int? id)
        {
            if (id == null)
                return NotFound();
            var tag = await this._tagsRepository.GetEmptyAsync(id);
            if (tag == null)
                return NotFound();
            return Ok(tag);
        }

        // POST api/Tag
        public async Task<IHttpActionResult> Post([FromBody] Tag tag)
        {
            if (tag == null)
                return NotFound();
            this._tagsRepository.Add(tag);
            await this._tagsRepository.SaveAsync();
            return Ok(tag);
        }

        // PUT api/Tag
        public async Task<IHttpActionResult> Put([FromBody] Tag tag)
        {
            if (tag == null)
                return NotFound();
            this._tagsRepository.Update(tag);
            await this._tagsRepository.SaveAsync();
            return Ok(tag);
        }

        // DELETE api/Tag/5
        public async Task<IHttpActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            await this._tagsRepository.DeleteAsync(id);
            await this._tagsRepository.SaveAsync();
            return Ok();
        }

        [HttpGet]
        [Route("api/Tag/Pages")]
        public async Task<IHttpActionResult> PagesCount()
        {
            var query = this._tagsRepository.GetAllQueryable();
            int pages = await Pagination.CountPagesAsync(query, StaticImfo.PageSize);
            return Ok(pages);
        }

        [HttpGet]
        [Route("api/Tag/Page/{number}")]
        public async Task<IHttpActionResult> GetPage(int number)
        {
            if (number > StaticImfo.PageSize)
                return BadRequest();
            var query = this._tagsRepository.GetAllQueryable();
            var myPage = Pagination.Page(query.OrderBy(c => c.ID), number, StaticImfo.PageSize);
            return Ok(myPage);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._tagsRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CBProject/Controllers/TagsController.cs
using AutoMapper;
using CBProject.HelperClasses.Interfaces;
using CBProject.Models.EntityModels;
using CBProject.Models.ViewModels;
using CBProject.Repositories;
using CBProject.Repositories.IdentityRepos.Interfaces;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CBProject.Controllers
{
    [Authorize]
    public class TagsController : Controller
    {
        private readonly TagsRepository _tagsRepo;
        private readonly VideosRepository _videoRepo;
        public TagsController(IUnitOfWork unitOfWork, IUsersRepo usersRepo)
        {
            this._tagsRepo = unitOfWork.Tags;
            this._videoRepo = unitOfWork.Videos;
        }
        public async Task<ActionResult> Index()
        {
            return View();
        }
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = await this._tagsRepo.GetAsync(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }
        public ActionResult Create()
        {
            var viewModel = new TagViewModel();
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = Mapper.Map<TagViewModel, Tag>(viewModel);
                this._tagsRepo.Add(tag);
                await this._tagsRepo.SaveAsync();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = await this._tagsRepo.GetAsync(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            var viewModel = Mapper.Map<Tag, TagViewModel>(tag);
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = Mapper.Map<TagViewModel, Tag>(viewModel);
                this._tagsRepo.Update(tag);
                await this._tagsRepo.SaveAsync();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = await this._tagsRepo.GetAsync(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            this._tagsRepo.Delete(id);
            await this._tagsRepo.SaveAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._tagsRepo.Dispose();
                this._videoRepo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CBProject/Controllers/VideosController.cs
using AutoMapper;
using CBProject.HelperClasses;
using CBProject.HelperClasses.Interfaces;
using CBProject.Models;
using CBProject.Models.ViewModels;
using CBProject.Repositories;
using CBProject.Repositories.IdentityRepos;
using CBProject.Repositories.IdentityRepos.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CBProject.Controllers
{
    public class VideosController : Controller
    {
        private readonly VideosRepository _videoRepo;
        private readonly UsersRepo _usersRepo;
        private readonly CategoriesRepository _categoriesRepo;
        private readonly TagsRepository _tagsRepo;
        private readonly ReviewsRepository _reviewRepo;
        private readonly RatingsRepository _ratingsRepo;
        private RequirementsRepository _requirementsRepo;
        public VideosController(IUnitOfWork unitOfWork, IUsersRepo usersRepo)
        {
            this._videoRepo = unitOfWork.Videos;
            this._usersRepo = (UsersRepo)usersRepo;
            this._categoriesRepo = unitOfWork.Categories;
            this._tagsRepo = unitOfWork.Tags;
            this._reviewRepo = unitOfWork.Reviews;
            this._ratingsRepo = unitOfWork.Ratings;
            this._requirementsRepo = unitOfWork.Requirements;
        }
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View();
        }
        public async Task<ActionResult> PublicDetails(int? id)
        {
            if (id == null)
                throw new ArgumentNullException(nameof(id));
            Video video = await this._videoRepo.GetAsync(id);
            if (video == null)
                throw new ArgumentNullException(nameof(video));
            var viewModel = Mapper.Map<Video, VideoViewModel>(video);
            List<Rating> ratings = (List<Rating>)await this._ratingsRepo.GetAllFromVideoAsync(video);
            float sum = 0.0f;
            foreach (var rating in ratings)
            {
                sum += rating.Rate;
            }
            viewModel.Rate = sum / ratings.Count;
            viewModel.Requirements = await this._videoRepo.GetRequirementsAsync(id);
            var videoPath = Server.MapPath($"~{viewModel.VideoPath}");
            viewModel.Duration = VideoEditor.Duration(videoPath);
            return View("PublicDetails", viewModel);
        }
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await this._videoRepo.GetAsync(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            var viewModel = Mapper.Map<Video, VideoViewModel>(video);
            viewModel.OtherUsers = await this._usersRepo.GetAllAsync();
            viewModel.OtherCategory = await this._categoriesRepo.GetAllAsync();
            viewModel.Requirements = await this._videoRepo.GetRequirementsAsync(video.ID);
            return View(viewModel);
        }
        public async Task<ActionResult> Create()
        {
            var viewModel = new VideoViewModel();
            viewModel.OtherUsers = await this._usersRepo.GetAllAsync();
            viewModel.OtherCategory = await this._categoriesRepo.GetAllAsync();
            viewModel.UploadDate = DateTime.Today;
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VideoViewModel viewModel, HttpPostedFileBase VideoImageFile, HttpPostedFileBase VideoFile)
        {
            if (ModelState.IsValid)
            {
                // VideoImageFile
                if (VideoImageFile != null)
                {
                    viewModel.VideoImageFile = VideoImageFile;
                    string FileName = Path.GetFileNameWithoutExtension(VideoFile.FileName);
                    string FileExtension = Path.GetExtension(viewModel.VideoImageFile.FileName);
                    FileName = FileName + FileExtension;
                    viewModel.VideoImagePath = (StaticImfo.VideoImagePath + FileName).Trim();
                    viewModel.VideoImageFile.SaveAs(Server.MapPath(viewModel.VideoImagePath));
                }
                // VideoFile
                if (VideoFile != null)
                {
                    viewModel.VideoFile = VideoFile;
                    string FileName = Path.GetFileNameWithoutExtension(VideoFile.FileName);
                    string FileExtension = Path.GetExtension(viewModel.VideoFile.FileName);
                    FileName = FileName + FileExtension;
                    viewModel.VideoPath = (StaticImfo.VideoPath + FileName).Trim();
                    viewModel.VideoFile.SaveAs(Server.MapPath(viewModel.VideoPath));
                }
                var video = Mapper.Map<VideoViewModel, Video>(viewModel);
                this._videoRepo.Add(video);
                await this._videoRepo.SaveAsync();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await this._videoRepo.GetAsync(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            var viewModel = Mapper.Map<Video, VideoViewModel>(video);
            viewModel.OtherUsers = await this._usersRepo.GetAllAsync();
            viewModel.OtherCategory = await this._categoriesRepo.GetAllAsync();
            viewModel.Requirements = await this._videoRepo.GetRequirementsAsync(video.ID);
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(VideoViewModel viewModel, HttpPostedFileBase VideoImageFile, HttpPostedFileBase VideoFile)
        {
            if (ModelState.IsValid)
            {
                // VideoImageFile
                var imgFile = false;
                if (VideoImageFile != null)
                {
                    viewModel.VideoImageFile = VideoImageFile;
                    string FileName = Path.GetFileNameWithoutExtension(VideoImageFile.FileName);
                    string FileExtension = Path.GetExtension(VideoImageFile.FileName);
                    FileName = FileName + FileExtension;
                    viewModel.VideoImagePath = (StaticImfo.VideoImagePath + FileName).Trim();
                    viewModel.VideoImageFile.SaveAs(Server.MapPath(viewModel.VideoImagePath));
                    imgFile = true;
                }
                // VideoFile
                var videoFile = false;
                if (VideoFile != null)
                {
                    viewModel.VideoFile = VideoFile;
                    string FileName = Path.GetFileNameWithoutExtension(VideoFile.FileName);
                    string FileExtension = Path.GetExtension(VideoFile.FileName);
                    FileName = FileName + FileExtension;
                    viewModel.VideoPath = (viewModel.VideoPath = StaticImfo.VideoPath + FileName).Trim();
                    viewModel.VideoFile.SaveAs(Server.MapPath(viewModel.VideoPath));
                    videoFile = true;
                }
                var imgFileOld = (await this._videoRepo.GetAsync(viewModel.ID)).VideoImagePath;
                var vidFileOld = (await this._videoRepo.GetAsync(viewModel.ID)).VideoPath;
                if (!imgFile) viewModel.VideoImagePath = imgFileOld;
                else
                {
                    FileInfo img = new FileInfo(HttpRuntime.AppDomainAppPath + imgFileOld);
                    if (img.Exists)
                    {
                        img.Delete();
                    }
                }
                if (!videoFile) viewModel.VideoPath = vidFileOld;
                else
                {
                    FileInfo file = new FileInfo(HttpRuntime.AppDomainAppPath + vidFileOld);
                    if (file.Exists)
                    {
                        file.Delete();
                    }
                }
                var video = Mapper.Map<VideoViewModel, Video>(viewModel);
                video.UploadDate = viewModel.UploadDate;
                await this._videoRepo.UpdateAsync(video);
                await this._videoRepo.SaveAsync();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = await this._videoRepo.GetAsync(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var video = await this._videoRepo.GetAsync(id);
            FileInfo img = new FileInfo(HttpRuntime.AppDomainAppPath + video.VideoImagePath);
            if (img.Exists)
            {
                img.Delete();
            }
            FileInfo file = new FileInfo(HttpRuntime.AppDomainAppPath + video.VideoPath);
            if (file.Exists)
            {
                file.Delete();
            }
            this._videoRepo.Delete(id);
            await this._videoRepo.SaveAsync();
            return RedirectToAction("Index");
        }
        [Authorize]
        [HttpPost]

CBProject/Views/Videos/Create.cshtml
@model CBProject.Models.ViewModels.VideoViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Video</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Upload Image Video", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <input type="file" name="VideoImageFile" ) />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Upload Video", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <input type="file" name="VideoFile" ) />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreatorId, "Creator", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CreatorId, new SelectList(Model.OtherUsers, "Id", "FullName"), htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.OtherCategory, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CBProject/Views/Videos/Edit.cshtml
@model CBProject.Models.ViewModels.VideoViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script type="text/javascript" src="~/Scripts/Servicies.js"></script>


@using (Html.BeginForm("Edit", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="VideoImageFile" ) />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="VideoFile" ) />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, "CreatorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CreatorId, new SelectList(@Model.OtherUsers, "ID", "FullName"), null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(@Model.OtherCategory, "ID", "NAME"), null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class=" class=" form-horizontal"">
    <div class="form-group">
        @Html.Label("Add Requrement", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea class="form-control rounded-0" id="add-requirement-textarea-Video" rows="2"></textarea>
            <br />
            <button class="btn btn-dark" onclick="addRequirements(@Model.ID, $('#add-requirement-textarea-Video').val(), 'video');">Add</button>
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.Label("Remove Requirement", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="remove-requirement-textarea-Video">
                @foreach (var req in Model.Requirements)
                {
                    <option value="@req.ID">@req.Content</option>
                }
            </select>
            <br />
            <button class="btn btn-dark" onclick="removeRequarements(@Model.ID, $('#remove-requirement-textarea-Video option:selected').val(), 'video');">Remove</button>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    
}

CBProject/Views/Videos/_Delete.cshtml
@model CBProject.Models.ViewModels.VideoViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VideoViewModel</h4>
    <hr />

    @using (Html.BeginForm("Delete", "Videos", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Thumbnail)
            </dt>

            <dd style="margin: 5px; text-align:center;">
                @Html.DisplayFor(model => model.Thumbnail)
                <img alt="video" src="@Html.DisplayFor(model => model.Thumbnail)" height="100" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.VideoImagePath)
            </dt>

            <dd style="margin: 5px; text-align:center;">
                @Html.DisplayFor(model => model.VideoImagePath)
                <img alt="video" src="@Html.DisplayFor(model => model.VideoImagePath)" height="100" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.VideoPath)
            </dt>

            <dd style="margin: 5px; text-align:center;">
                @Html.DisplayFor(model => model.VideoPath)
                <video height="150" controls preload="none" poster="@Html.DisplayFor(model => model.Thumbnail)">
                    <source src="@Html.DisplayFor(model => model.VideoPath)" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UploadDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UploadDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Creator)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Creator.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Url)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Url)
            </dd>
        </dl>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

CBProject/Views/Videos/_Review.cshtml
@model CBProject.Models.ViewModels.VideoViewModel

@using (Html.BeginForm("AddReview", "Videos", new { videoId = @Model.ID }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => @Model.ID)

    <div style="margin: 7px;">
        <i class="fas fa-pencil-alt prefix" style="margin-left: 11%;"></i>
        <textarea class="md-textarea form-control" rows="3" name="comment" style="margin: 0 auto;"></textarea>
        <input type="submit" value="Save" class="btn btn-default" style="margin-left: 80%; margin-top: 11px;" />
    </div>
}

CBProject/Views/Videos/_Tag.cshtml
@model CBProject.Models.ViewModels.VideoViewModel

@using (Html.BeginForm("AddTag", "Videos", new { videoId = @Model.ID }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => @Model.ID)

    <div style="margin: 7px;">
        <i class="fas fa-pencil-alt prefix" style="margin-left: 11%;"></i>
        <textarea class="md-textarea form-control" rows="3" name="title" style="margin: 0 auto;"></textarea>
        <input type="submit" value="Save" class="btn btn-default" style="margin-left: 80%; margin-top: 11px;" />
    </div>
}